# Generated by Django 4.1.4 on 2023-02-17 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='image',
        ),
        migrations.AddField(
            model_name='carousel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.product'),
        ),
    ]
