# Generated by Django 4.1.4 on 2023-02-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_remove_carousel_image_carousel_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='title',
        ),
    ]
