# Generated by Django 4.1.4 on 2023-02-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_remove_carousel_description_remove_carousel_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
